version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - npm install -g yarn
      - chmod +x bash/makeConfig.sh
      - bash/makeConfig.sh
      - yarn
      - cd assets/lambda/layers/aws/nodejs
      - yarn
      - wait $!
      - cd ../../../../..
      - yarn build
      - wait $!
  build:
    commands:
      - npx cdk deploy BooksLayers --require-approval never
      - npx cdk deploy BooksDynamoDb --require-approval never
      - npx cdk deploy BooksAppsyncPre --require-approval never
      - npx cdk deploy BooksCognito --require-approval never
      - npx cdk deploy BooksAppsync --require-approval never
      - npx cdk deploy BooksAppsyncResolvers --require-approval never
      - npx cdk deploy BooksCognitoIam --require-approval never
      
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
